### ISSUE TITLE
How can I import the whole library and not every component separately? 

### ISSUE THREAD

**Issue by raikm** [ulissesferreira/moon#5]
First of all thank you for your `dev.to` blog article since it helped me a lot to build something similar! I was wondering how I can Import the whole library since I get the following error when I am doing: 

```
import Moon from "@ulissesferreira/moon";
```

```
Uncaught SyntaxError: The requested module '/@fs/Users/raik/Documents/GitHubtest-tool/node_modules/.vite/@ulissesferreira_moon.js?v=405e62b1' does not provide an export named 'default'
```

**Comment by ulissesferreira** [comment]
Sorry for the delay, have been on vacation and away from Github.

Hmmm the idea of having things imported separately is for Tree Shaking support. I guess in the `index.js` you could export the whole library as one big thing and then use it like `Moon.Button`.

I don't really know what the use case would be though 🤔
