### ISSUE TITLE
Can i transform this lib to Universal lib (vue2/3)?

### ISSUE THREAD

**Issue by kostia7alania** [ulissesferreira/moon#6]
My question is here
https://stackoverflow.com/questions/69653227/how-to-create-a-universal-component-library-for-vue-2-vue-3

**Comment by ulissesferreira** [comment]
Hmmm that is an interesting question. I have never tried to create something that could support both Vue 2 and Vue 3. I believe that you could achieve that using the default Vue CLI with the `library` target mode.

Read more about Vue CLI's documentation [here](https://cli.vuejs.org/guide/build-targets.html#library)

If you use the latest Vue CLI I believe you can build something backwards compatible. 

Disadvantage: I don't think you could use Vite without some hacking around.

**Comment by ulissesferreira** [comment]
Also @kostia7alania the example that you linked there seems to originate from an article in dev.to you might get some info there:

https://dev.to/alvarosaburido/how-to-create-a-universal-library-for-vue-2-3-4lf8
